version: "3"
services:
  cupsd:
    image: printerbox_cupsd:v1
    privileged: true
    volumes:
      - ./printerbox_cupsd/scripts:/scripts
      - /dev:/dev 
      - /var/run/dbus:/var/run/dbus
    entrypoint: /scripts/start_cupsd.sh
    networks:
      - printerbox_network
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  sortkaffe:
    build: printerbox_python
    privileged: true
    volumes:
      - ./printerbox_cupsd/labels:/labels 
      - /dev:/dev 
      - ./src:/src 
      - ./config:/config 
    entrypoint: python
    networks:
      - printerbox_network
    command: /src/printerbox.py
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      options:
        max-size: "10m"
        max-file: "3"
networks:
  printerbox_network:
