version: "3"
services:
  cupsd:
    image: printerbox_cupsd:v1
    privileged: true
    volumes:
      - ./printerbox_cupsd/scripts:/scripts
      - /dev:/dev 
      - /var/run/dbus:/var/run/dbus
    entrypoint: /scripts/start_cupsd.sh
    networks:
      - printerbox_network
    restart: unless-stopped
  sortkaffe:
    build: printerbox_python
    volumes:
      - ./printerbox_cupsd/labels:/labels 
      - ./src:/src 
    entrypoint: python
    networks:
      - printerbox_network
    command: /src/printerbox.py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
networks:
  printerbox_network:
